name: Publish php81 Image
on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    name: Release OCI image
    runs-on: ubuntu-latest

    outputs:
      image-refs: ${{ steps.emit-refs.outputs.image-refs }}

    steps:
    - uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        username: ctadeu
        password: ${{ secrets.DOCKER_LOGIN_PASS }}

    - name: Extract metadata (tags, labels) for Docker
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      with:
        images: docker.io/ctadeu/php81

    - uses: cpanato/chainguard-images-actions/apko-snapshot@updates
      with:
        config: php81/apko.yaml
        base-tag: docker.io/ctadeu/php81
        package-version-tag: php81
        registry: docker.io
        username: ctadeu
        token: ${{ secrets.DOCKER_LOGIN_PASS }}

    - name: Emit Image Refs output
      id: emit-refs
      run: |
          cat apko.images | sed 's/$/\n/g' | grep -v '^$' | jq -R -s -c 'split("\n")[:-1]' | jq .
          echo ::set-output name=image-refs::$(cat apko.images | sed 's/$/\n/g' | grep -v '^$' | jq -R -s -c 'split("\n")[:-1]')
